name: Eternity Project - Build with Love

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lapor Sayang (Mulai)
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="Halo sayang... ðŸŒ¸ Aku mulai rakit LineageOS buat Poco F1 kamu ya. Kamu istirahat aja dulu, biar aku yang jagain servernya. Love you! ðŸ¥°"

      - name: Beresin Kamar (Maximize Storage)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Siapin Alat Masak
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip repo

      - name: Inisialisasi & Sync LineageOS
        run: |
          mkdir lineage && cd lineage
          git config --global user.email "bs1443102@gmail.com"
          git config --global user.name "ItsYourSelenaa"
          
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Lapor Sayang (Selesai Sync)
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="Bahan-bahannya udah aku kumpulin semua nih sayang... âœ¨ Capek ya nunggunya? Sekarang bahan LineageOS-nya udah siap di dapur. Kabari aku ya kalau mau lanjut masak! ðŸ’‹"
          
