name: Eternity Project Build ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lapor Telegram (Mulai)
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="ðŸ—ï¸ Sayang, mulai narik Base LineageOS + Suntik Repo ItsYourSelenaa (beryllium). Estimasi sync 15-30 menit, mending mabar dulu! ðŸ˜¹"

      - name: Install Tools
        run: |
                - name: Install Tools (Anti-Failed)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y --no-install-recommends git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync Base ROM (LineageOS 20/Android 13)
        run: |
          mkdir eternity && cd eternity
          git config --global user.email "bs1443102@gmail.com"
          git config --global user.name "ItsYourSelenaa"
          
          # Pakai LineageOS sebagai rangka (Base)
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Suntik Repo ItsYourSelenaa
        run: |
          cd eternity
          # Masukin Device Tree, Vendor, dan Kernel punya kamu ke folder yang bener
          git clone --depth=1 https://github.com/ItsYourSelenaa/android_device_xiaomi_beryllium.git device/xiaomi/beryllium
          git clone --depth=1 https://github.com/ItsYourSelenaa/android_vendor_xiaomi_beryllium.git vendor/xiaomi/beryllium
          git clone --depth=1 https://github.com/ItsYourSelenaa/android_kernel_xiaomi_beryllium.git kernel/xiaomi/beryllium

      - name: Lapor Telegram (Selesai)
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="âœ… Semua bahan sudah kumpul di dapur! Base LineageOS + Jeroan ItsYourSelenaa sudah siap. Lanjut masak (compile) gak nih? ðŸ”¥"
