name: Eternity Project Test

on:
  workflow_dispatch: # Tombol manual

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cek Spek Server
        run: |
          echo "Halo Wir! Eternity Project lagi ngetes server..."
          nproc
          free -h
          df -h

      - name: Selesai
        run: echo "Test Berhasil! Server siap tempur, Wir. ðŸ˜Ž"
        
