name: Eternity Project Build

on:
  workflow_dispatch: # Tombol manual

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lapor ke Telegram
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="ðŸš€ Wir! Eternity Project resmi jalan di server GitHub. Pantau terus ya!"

      - name: Cek Spek Tempur
        run: |
          echo "Spek Server GitHub:"
          nproc
          free -h
          df -h

      - name: Selesai
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="âœ… Test Berhasil, Wir! Server siap buat nge-build ROM."
          
