name: Eternity Project Build ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lapor Telegram (Mulai)
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="ðŸ—ï¸ Bos, mulai narik (sync) Source Code ROM Nusantara buat Poco F1. Proses ini agak lama, silakan lanjut skrol imphnen dulu! ðŸ˜¹"

      - name: Install Tools & Repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Inisialisasi & Sync (Mini)
        run: |
          mkdir eternity && cd eternity
          git config --global user.email "email_kamu@gmail.com"
          git config --global user.name "ItsYourSelenaa"
          
          # Kita pakai --depth=1 biar gak menuhi storage
          repo init -u https://github.com/NusantaraProject-ROM/android_manifest -b 13 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Lapor Telegram (Selesai Sync)
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="âœ… Sync Berhasil, Bos! Source code udah di gudang. Siap lanjut ke tahap racik (compile)?"
          
