name: Eternity Project Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
    - name: Kirim Notif Mulai
      run: |
        curl -s "https://api.telegram.org/bot${{ secrets.8536809781:AAEzX5PMEkJIbz6XxYG6gNc5tupfu0YNabo }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="ðŸš€ Wir, Eternity Project buat Poco F1 (beryllium) mulai dibangun! Silakan lanjut skrol imphnen, nanti dikabari lagi kalau kelar. ðŸ˜Ž"

    - name: Setup Lingkungan & Build
      run: |
        # Di sini nanti kita pasang script sync & build yang beneran
        # Sementara kita simulasiin proses berat 1 menit
        echo "Lagi narik source code..."
        sleep 60 

    - name: Kirim Hasil Build
      run: |
        curl -s "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="âœ… Build SELESAI, Wir! Link download bakal muncul di tab Actions GitHub kamu. Selamat flashing! ðŸ˜¹"
        
